excerpt_separator: <!--more-->
include: ["_pages"]
permalink: /post/:title/
url: http://theblog.github.io
exclude:
  - _dist
  - node_modules
  - notes
  - src
  - .eslintrc
  - .gitignore
  - gulpfile.js
  - package.json
  - package-lock.json
  - README.md